// src/v1/constants/index.ts

export const CRAWLER_CONFIG = {
  DEFAULT_FETCH_TIMEOUT_MS: 2500,
  FALLBACK_FETCH_TIMEOUT_MS: 4000,
  MAX_PAGE_CONTENT_BYTES: 5 * 1024 * 1024, // 5MB limit
  CONCURRENT_CRAWL_BATCH_SIZE: 5,
} as const;

export const INGEST_CONFIG = {
  MAX_TEXT_SIZE_BYTES: 10 * 1024 * 1024, // 10MB limit
  MAX_CHUNK_TEXT_CHARS: 24000,
  DEFAULT_EMBEDDING_BATCH_SIZE: 50,
  DEFAULT_VECTOR_UPSERT_BATCH_SIZE: 50,
} as const;

export const CACHE_CONFIG = {
  DEFAULT_CACHE_TTL_SECONDS: 86400, // 24 hours
  SEMANTIC_SIMILARITY_THRESHOLD: 0.95,
} as const;

export const RETRY_CONFIG = {
  DEFAULT_MAX_ATTEMPTS: 3,
  DEFAULT_BASE_MS: 250,
  DEFAULT_MAX_MS: 3000,
} as const;
